### ISSUE TITLE
Redacting value types for PII in the domain model (follow-up to #751)

### ISSUE THREAD

**Issue by cybergrouch** [cybergrouch/skopeo#801]
Follow-up to #751 (open question 3, PII scrubbing). #751 decided the layering: **narrow the sinks** and **keep PII out of authored messages** are the primary controls and gate enabling Sentry in production. This issue is layer 2 — *defence in depth*, deliberately deferred because its value is preventing a future mistake rather than fixing a current one.

## The mistake this prevents

Every PII-carrying domain type is a Kotlin `data class`, so `toString()` is auto-generated over **every** field. That makes this one line a permanent plain-text leak of a Firebase UID and a date of birth:

```kotlin
logger.info { "provisioned $user" }
```

Nothing in the build would object. A redacting `toString()` removes the whole class of mistake, rather than relying on reviewers to catch each instance.

Note what this does **not** cover, so the scope stays honest: Sentry captures the raw HTTP body, headers and stack-trace locals *outside* the type system, and structured logging that writes JSON fields bypasses `toString()` entirely. Those are handled by the sink-narrowing work in #751. This issue is not a substitute for it.

## Scope: domain model only

`common/dto/**` and `repository/persistence/**` keep plain `String`/`LocalDate`. Under the #633 layering each field has three representations, so a full sweep is a genuine refactor with mappers to update at both boundaries — not worth it for a defence-in-depth layer. The domain model is where accidental logging actually happens, because it is what services hold.

### Targets

| Type | Field(s) | File |
| --- | --- | --- |
| `User` | `firebaseUid`, `dateOfBirth` | `domain/model/UserDomain.kt` |
| `ProvisionUserCommand` | `firebaseUid`, `dateOfBirth`, `email` | `domain/model/UserDomain.kt` |
| `ProfilePatch` | `dateOfBirth` | `domain/model/UserDomain.kt` |
| `CreatePlaceholderCommand` | `dateOfBirth` | `domain/model/UserDomain.kt` |
| `PendingAssessment` | `dateOfBirth` | `domain/model/RatingDomain.kt` |
| `Invite` | `email` | `domain/model/InviteDomain.kt` |

`User` is the highest-value single target — it carries both sensitive fields and is the type threaded through nearly every service.

## Three findings that shape the work

**1. There is no wire risk. Verified.** None of the six types above is `@Serializable` — the annotated models in `domain/model` (`Rating`, `Team`, `MatchScore`, `SetScore`, `TiebreakScore`, `Level`, `PlayerProfile`, `RatingCalculationOptions`, …) carry no PII. So wrapping these fields cannot change any JSON payload, and **no custom serializers are needed**. This is what makes the change cheap, and it's the first thing to re-verify if the scope grows.

This also keeps faith with the existing decision that the wire-contract DTOs are an intentional allowlist — nothing here proposes mirroring model types onto the wire.

**2. `Email` as a value class does not fit, and shouldn't be forced.** Email is not a typed field in the domain: it lives as `ContactInfo.value` / `Contact.value`, a generic string discriminated by `ContactType`. Contacts are a polymorphic append-only sub-resource, so introducing an `Email` type there would mean either splitting the contact model by type or wrapping every contact value including non-sensitive ones.

Do the simpler thing instead: **override `toString()` on `ContactInfo` and `Contact`** to redact `value` while keeping `type`, `status` and `isPrimary` visible — those are the fields that make a log line useful. `Invite.email`, which *is* a dedicated field, can take the value class.

**3. This introduces a pattern the codebase does not yet have.** There is currently no `value class` anywhere in `src/main/kotlin`. So establish it once, deliberately, with a short KDoc explaining why redaction lives in the type — otherwise the next person adding a sensitive field won't know the convention exists. Two things to get right:

- A `value class` **auto-generates a `toString()` that includes the wrapped value**, so the override is mandatory, not optional. This is the easy thing to forget and the whole point of the exercise.
- `DateOfBirth` needs an explicit accessor for the real uses — age computation and the rating/seeding paths — so the wrapper doesn't turn into friction. Check the call sites before choosing the accessor name.

## Enforcement

A convention that isn't tested decays. Add a reflective test that walks the domain model, finds data classes with a field named `firebaseUid` / `dateOfBirth` / `email` (or typed with one of the new value classes), instantiates one with a known sentinel value, and asserts the sentinel does **not** appear in `toString()`. That makes a newly-added sensitive field fail the build rather than silently opt out.

## Acceptance criteria

> **⚠️ Superseded — see the closing comment.** These describe the *original* plan (`FirebaseUid` /
> `DateOfBirth` value classes on six domain types). That approach was replaced during implementation by a
> single generic `Redactable<T>`, because the original still required a hand-written `toString()` per model
> or mapper churn at both #633 boundaries. `User.dateOfBirth` (~126 occurrences) and `User.firebaseUid`
> (~238) were deliberately excluded on cost/benefit.
>
> The criteria are left here unedited as a record of what was planned. **Do not treat the unchecked boxes
> as outstanding work.** What shipped, what was excluded and why, and the site counts are all in the
> closing comment. The one genuinely outstanding item — a guard against new PII fields being added
> unwrapped — moved to #822.

- [ ] ~~`FirebaseUid` and `DateOfBirth` value classes exist~~ → replaced by a generic `Redactable<T>`.
- [ ] ~~The six types above use them~~ → a different, higher-value set was wrapped; see the closing comment.
- [x] `ContactInfo` and `Contact` no longer render their `value` — via the field's type, not a `toString()` override.
- [x] `Invite.email` uses a redacting type.
- [ ] ~~`User.toString()` reveals neither the Firebase UID nor the date of birth~~ → deliberately excluded.
- [ ] A guard test fails if a domain data class exposes a sensitive field → **moved to #822**.
- [x] No JSON payload changes; no custom serializer needed.
- [ ] ~~`DateOfBirth` has an accessor~~ → not applicable; `dateOfBirth` was not wrapped.
- [x] Documentation records that this is layer 2 and not a substitute for sink narrowing.

**Comment by cybergrouch** [comment]
## What was actually built — the criteria above describe a design we replaced

Closing the record, because the acceptance criteria in the body are from the **original** plan and were
deliberately superseded. Anyone reading them now would see nine unchecked boxes and reasonably conclude
the work was abandoned half-done. It wasn't; the approach changed.

### The design changed, for a good reason

The filed plan was `FirebaseUid` / `DateOfBirth` value classes on six domain types. The objection to that
was decisive: it still required a hand-written `toString()` per model — or, if the accessor types changed,
mapper churn at both #633 boundaries — which is ongoing boilerplate that fails silently the moment someone
adds a model and doesn't know the convention.

What shipped instead is one generic `Redactable<T>` in `common/redaction`. Because Kotlin generates a data
class's `toString()` from its constructor properties, and that generated method calls `toString()` on each
field, **making the field's type redact protects every containing model automatically** — no per-model
code, nothing to forget.

**The compiler plugin was tried first** and would have been better still (annotation, zero call-site
churn). It does not work on Kotlin 2.2.21, verified empirically rather than from the changelog:

| Version | Result |
| --- | --- |
| `1.13.0` (stable, targets 2.1.20) | `compileKotlin` fails — `AbstractMethodError` in the FIR checker |
| `1.14.0-alpha01` | main compiles, `compileTestKotlin` fails — `NoSuchMethodError` |

Revisit when a stable release targeting 2.2.x ships; the swap is delete-the-wrapper, add-annotations.
Explicitly **not** worth downgrading Kotlin for — this repo already pins its Gradle daemon to Java 21 for
detekt, and a second toolchain shackle for defence in depth is a bad trade.

### Wrapped, by what a leak would cost

| Target | Holds | Sites |
| --- | --- | --- |
| `IssuedApiKey.plaintext` | a **working partner API key** | 2 |
| `VerifiedFirebaseToken` `.email` + `.providerUid` | raw verified identity, built on every authenticated request | 8 main + 41 test |
| `Contact.value` **and** `ContactInfo.value` | email/phone — stored and incoming forms | 9 main + 6 test |
| `Invite.email` | invitee address | 3 |

Both contact forms were required: wrapping one alone leaves the other leaking, and services handle
`Contact` far more often than `ContactInfo`.

On `plaintext` — the field **cannot** be removed, which was asked during the work. Only the SHA-256 hash is
persisted, so it is the show-once delivery of the key and hashes are not reversible; deleting it makes a key
unusable the moment it is created. Its only exposure was `toString()`. Existing tests that *authenticate
using the returned key* still pass, so the wire is provably unchanged.

### Deliberately NOT wrapped — decisions, not omissions

| Excluded | Occurrences | Why |
| --- | --- | --- |
| `User.dateOfBirth` | ~126 | Cost/benefit. #806's clean-sources rule and `PiiLeakTest` already cover it, and a date of birth in a log is a materially smaller problem than a live credential. |
| `User.firebaseUid` | ~238 | Same, more so. |
| `UserName.value` | — | Display names are shown publicly on player pages anyway. |
| `UserIdentity.providerUid` | — | It is the join key the repository looks up by. |

### Against the original criteria

- ✅ `ContactInfo`/`Contact` no longer render their value — achieved by the field's type rather than a
  `toString()` override, which is strictly better.
- ✅ `Invite.email` uses a redacting type.
- ✅ No JSON payload changes; no custom serializer needed. Verified: none of the PII-carrying domain models
  are `@Serializable`, and no DTO or model is interpolated into a response body.
- ✅ `LOGGING_AND_METRICS.md` records this as layer 2 and not a substitute for sink narrowing (#806 wrote
  that line).
- ⛔️ `FirebaseUid`/`DateOfBirth` value classes, `User.toString()`, and a `DateOfBirth` accessor —
  **superseded**, see the exclusions above.
- ⛔️ The reflective guard test — **moved to #822**, which also needs a decision between a source scan, a
  reflective test, and a logger-interpolation scan.

### Two things worth carrying forward

**The accessor is `revealed`, not `value`.** `contact.value.value` was unreadable; `.revealed` states
intent, and `\.revealed` greps out every deliberate exposure point — currently 14 across 11 files, which
is exactly the list a reviewer wants.

**The type system does not catch string interpolation.** Wrapping `Contact.value` silently turned an
audit-log summary into `"Enabled EMAIL ***"` with no compile error; only `ContactServiceTest` caught it.
`ContactService` and `InviteService` both legitimately record the address in the audit table, so both are
now explicit `.revealed` unwraps with a comment. **Anyone wrapping further fields should run the full
suite rather than trusting a clean compile.**
